[workspace]
authors = ["TylerJost <taj159@gmail.com>"]
channels = ["conda-forge"]
name = "twim"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[tasks]

[dependencies]
pytorch-gpu = "*"
pandas = "*"
tqdm = "*"
matplotlib = "*"
spotipy = "*"
datasets = "*"
numpy = "*"
beautifulsoup4 = "*"
transformers = "*"

[pypi-dependencies]
ipykernel = "*"
twia = { path = ".", editable = true }